/*
 * Fenrir Api
 * 
 * This file was automatically generated using openapi generator. 
 * DO NOT EDIT MANUALLY.
 * Refer to: https://github.com/FenrirServer/Cloud.SdkTemplates
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Fenrir.Api.Model;
using Fenrir.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Fenrir.Api.Test.Model
{
    /// <summary>
    ///  Class for testing ApiToken
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ApiTokenTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ApiToken
        //private ApiToken instance;

        public ApiTokenTests()
        {
            // TODO uncomment below to create an instance of ApiToken
            //instance = new ApiToken();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ApiToken
        /// </summary>
        [Fact]
        public void ApiTokenInstanceTest()
        {
            // TODO uncomment below to test "IsType" ApiToken
            //Assert.IsType<ApiToken>(instance);
        }

        /// <summary>
        /// Test the property 'ApplicationUuid'
        /// </summary>
        [Fact]
        public void ApplicationUuidTest()
        {
            // TODO unit test for the property 'ApplicationUuid'
        }

        /// <summary>
        /// Test the property 'Created'
        /// </summary>
        [Fact]
        public void CreatedTest()
        {
            // TODO unit test for the property 'Created'
        }

        /// <summary>
        /// Test the property 'IsPublic'
        /// </summary>
        [Fact]
        public void IsPublicTest()
        {
            // TODO unit test for the property 'IsPublic'
        }

        /// <summary>
        /// Test the property 'Label'
        /// </summary>
        [Fact]
        public void LabelTest()
        {
            // TODO unit test for the property 'Label'
        }

        /// <summary>
        /// Test the property 'TokenPlaintext'
        /// </summary>
        [Fact]
        public void TokenPlaintextTest()
        {
            // TODO unit test for the property 'TokenPlaintext'
        }

        /// <summary>
        /// Test the property 'Updated'
        /// </summary>
        [Fact]
        public void UpdatedTest()
        {
            // TODO unit test for the property 'Updated'
        }

        /// <summary>
        /// Test the property 'Uuid'
        /// </summary>
        [Fact]
        public void UuidTest()
        {
            // TODO unit test for the property 'Uuid'
        }
    }
}
