/*
 * Fenrir Api
 * 
 * This file was automatically generated using openapi generator. 
 * DO NOT EDIT MANUALLY.
 * Refer to: https://github.com/FenrirServer/Cloud.SdkTemplates
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Fenrir.Api.Model;
using Fenrir.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Fenrir.Api.Test.Model
{
    /// <summary>
    ///  Class for testing ApiTokenListResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ApiTokenListResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ApiTokenListResponse
        //private ApiTokenListResponse instance;

        public ApiTokenListResponseTests()
        {
            // TODO uncomment below to create an instance of ApiTokenListResponse
            //instance = new ApiTokenListResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ApiTokenListResponse
        /// </summary>
        [Fact]
        public void ApiTokenListResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" ApiTokenListResponse
            //Assert.IsType<ApiTokenListResponse>(instance);
        }

        /// <summary>
        /// Test the property 'ApiTokens'
        /// </summary>
        [Fact]
        public void ApiTokensTest()
        {
            // TODO unit test for the property 'ApiTokens'
        }
    }
}
