/*
 * Fenrir Api
 * 
 * This file was automatically generated using openapi generator. 
 * DO NOT EDIT MANUALLY.
 * Refer to: https://github.com/FenrirServer/Cloud.SdkTemplates
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Fenrir.Api.Model;
using Fenrir.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Fenrir.Api.Test.Model
{
    /// <summary>
    ///  Class for testing ApiTokenResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ApiTokenResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ApiTokenResponse
        //private ApiTokenResponse instance;

        public ApiTokenResponseTests()
        {
            // TODO uncomment below to create an instance of ApiTokenResponse
            //instance = new ApiTokenResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ApiTokenResponse
        /// </summary>
        [Fact]
        public void ApiTokenResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" ApiTokenResponse
            //Assert.IsType<ApiTokenResponse>(instance);
        }

        /// <summary>
        /// Test the property 'ApiToken'
        /// </summary>
        [Fact]
        public void ApiTokenTest()
        {
            // TODO unit test for the property 'ApiToken'
        }
    }
}
