/*
 * Fenrir Api
 * 
 * This file was automatically generated using openapi generator. 
 * DO NOT EDIT MANUALLY.
 * Refer to: https://github.com/FenrirServer/Cloud.SdkTemplates
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Fenrir.Api.Model;
using Fenrir.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Fenrir.Api.Test.Model
{
    /// <summary>
    ///  Class for testing ApplicationInstanceResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ApplicationInstanceResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ApplicationInstanceResponse
        //private ApplicationInstanceResponse instance;

        public ApplicationInstanceResponseTests()
        {
            // TODO uncomment below to create an instance of ApplicationInstanceResponse
            //instance = new ApplicationInstanceResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ApplicationInstanceResponse
        /// </summary>
        [Fact]
        public void ApplicationInstanceResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" ApplicationInstanceResponse
            //Assert.IsType<ApplicationInstanceResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Instance'
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO unit test for the property 'Instance'
        }
    }
}
