/*
 * Fenrir Api
 * 
 * This file was automatically generated using openapi generator. 
 * DO NOT EDIT MANUALLY.
 * Refer to: https://github.com/FenrirServer/Cloud.SdkTemplates
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Fenrir.Api.Model;
using Fenrir.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Fenrir.Api.Test.Model
{
    /// <summary>
    ///  Class for testing ApplicationInstanceStats
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ApplicationInstanceStatsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ApplicationInstanceStats
        //private ApplicationInstanceStats instance;

        public ApplicationInstanceStatsTests()
        {
            // TODO uncomment below to create an instance of ApplicationInstanceStats
            //instance = new ApplicationInstanceStats();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ApplicationInstanceStats
        /// </summary>
        [Fact]
        public void ApplicationInstanceStatsInstanceTest()
        {
            // TODO uncomment below to test "IsType" ApplicationInstanceStats
            //Assert.IsType<ApplicationInstanceStats>(instance);
        }

        /// <summary>
        /// Test the property 'Ccu'
        /// </summary>
        [Fact]
        public void CcuTest()
        {
            // TODO unit test for the property 'Ccu'
        }

        /// <summary>
        /// Test the property 'Cpu'
        /// </summary>
        [Fact]
        public void CpuTest()
        {
            // TODO unit test for the property 'Cpu'
        }

        /// <summary>
        /// Test the property 'Mem'
        /// </summary>
        [Fact]
        public void MemTest()
        {
            // TODO unit test for the property 'Mem'
        }
    }
}
