/*
 * Fenrir Api
 * 
 * This file was automatically generated using openapi generator. 
 * DO NOT EDIT MANUALLY.
 * Refer to: https://github.com/FenrirServer/Cloud.SdkTemplates
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Fenrir.Api.Model;
using Fenrir.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Fenrir.Api.Test.Model
{
    /// <summary>
    ///  Class for testing ApplicationStats
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ApplicationStatsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ApplicationStats
        //private ApplicationStats instance;

        public ApplicationStatsTests()
        {
            // TODO uncomment below to create an instance of ApplicationStats
            //instance = new ApplicationStats();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ApplicationStats
        /// </summary>
        [Fact]
        public void ApplicationStatsInstanceTest()
        {
            // TODO uncomment below to test "IsType" ApplicationStats
            //Assert.IsType<ApplicationStats>(instance);
        }

        /// <summary>
        /// Test the property 'CcuTotal'
        /// </summary>
        [Fact]
        public void CcuTotalTest()
        {
            // TODO unit test for the property 'CcuTotal'
        }

        /// <summary>
        /// Test the property 'CpuAvg'
        /// </summary>
        [Fact]
        public void CpuAvgTest()
        {
            // TODO unit test for the property 'CpuAvg'
        }

        /// <summary>
        /// Test the property 'MemAvg'
        /// </summary>
        [Fact]
        public void MemAvgTest()
        {
            // TODO unit test for the property 'MemAvg'
        }

        /// <summary>
        /// Test the property 'NumDeployments'
        /// </summary>
        [Fact]
        public void NumDeploymentsTest()
        {
            // TODO unit test for the property 'NumDeployments'
        }

        /// <summary>
        /// Test the property 'NumInstances'
        /// </summary>
        [Fact]
        public void NumInstancesTest()
        {
            // TODO unit test for the property 'NumInstances'
        }
    }
}
