/*
 * Fenrir Api
 * 
 * This file was automatically generated using openapi generator. 
 * DO NOT EDIT MANUALLY.
 * Refer to: https://github.com/FenrirServer/Cloud.SdkTemplates
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Fenrir.Api.Model;
using Fenrir.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Fenrir.Api.Test.Model
{
    /// <summary>
    ///  Class for testing ApplicationConfiguration
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ApplicationConfigurationTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ApplicationConfiguration
        //private ApplicationConfiguration instance;

        public ApplicationConfigurationTests()
        {
            // TODO uncomment below to create an instance of ApplicationConfiguration
            //instance = new ApplicationConfiguration();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ApplicationConfiguration
        /// </summary>
        [Fact]
        public void ApplicationConfigurationInstanceTest()
        {
            // TODO uncomment below to test "IsType" ApplicationConfiguration
            //Assert.IsType<ApplicationConfiguration>(instance);
        }

        /// <summary>
        /// Test the property 'ApplicationUuid'
        /// </summary>
        [Fact]
        public void ApplicationUuidTest()
        {
            // TODO unit test for the property 'ApplicationUuid'
        }

        /// <summary>
        /// Test the property 'Created'
        /// </summary>
        [Fact]
        public void CreatedTest()
        {
            // TODO unit test for the property 'Created'
        }

        /// <summary>
        /// Test the property 'MaxInstances'
        /// </summary>
        [Fact]
        public void MaxInstancesTest()
        {
            // TODO unit test for the property 'MaxInstances'
        }

        /// <summary>
        /// Test the property 'MinInstances'
        /// </summary>
        [Fact]
        public void MinInstancesTest()
        {
            // TODO unit test for the property 'MinInstances'
        }

        /// <summary>
        /// Test the property 'Ports'
        /// </summary>
        [Fact]
        public void PortsTest()
        {
            // TODO unit test for the property 'Ports'
        }

        /// <summary>
        /// Test the property 'Updated'
        /// </summary>
        [Fact]
        public void UpdatedTest()
        {
            // TODO unit test for the property 'Updated'
        }

        /// <summary>
        /// Test the property 'Uuid'
        /// </summary>
        [Fact]
        public void UuidTest()
        {
            // TODO unit test for the property 'Uuid'
        }
    }
}
