/*
 * Fenrir Api
 * 
 * This file was automatically generated using openapi generator. 
 * DO NOT EDIT MANUALLY.
 * Refer to: https://github.com/FenrirServer/Cloud.SdkTemplates
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Fenrir.Api.Model;
using Fenrir.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Fenrir.Api.Test.Model
{
    /// <summary>
    ///  Class for testing ApplicationInstanceListResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ApplicationInstanceListResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ApplicationInstanceListResponse
        //private ApplicationInstanceListResponse instance;

        public ApplicationInstanceListResponseTests()
        {
            // TODO uncomment below to create an instance of ApplicationInstanceListResponse
            //instance = new ApplicationInstanceListResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ApplicationInstanceListResponse
        /// </summary>
        [Fact]
        public void ApplicationInstanceListResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" ApplicationInstanceListResponse
            //Assert.IsType<ApplicationInstanceListResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Instances'
        /// </summary>
        [Fact]
        public void InstancesTest()
        {
            // TODO unit test for the property 'Instances'
        }
    }
}
