/*
 * Fenrir Api
 * 
 * This file was automatically generated using openapi generator. 
 * DO NOT EDIT MANUALLY.
 * Refer to: https://github.com/FenrirServer/Cloud.SdkTemplates
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Fenrir.Api.Model;
using Fenrir.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Fenrir.Api.Test.Model
{
    /// <summary>
    ///  Class for testing ApplicationConfigurationResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ApplicationConfigurationResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ApplicationConfigurationResponse
        //private ApplicationConfigurationResponse instance;

        public ApplicationConfigurationResponseTests()
        {
            // TODO uncomment below to create an instance of ApplicationConfigurationResponse
            //instance = new ApplicationConfigurationResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ApplicationConfigurationResponse
        /// </summary>
        [Fact]
        public void ApplicationConfigurationResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" ApplicationConfigurationResponse
            //Assert.IsType<ApplicationConfigurationResponse>(instance);
        }

        /// <summary>
        /// Test the property 'VarConfiguration'
        /// </summary>
        [Fact]
        public void VarConfigurationTest()
        {
            // TODO unit test for the property 'VarConfiguration'
        }
    }
}
