/*
 * Fenrir Api
 * 
 * This file was automatically generated using openapi generator. 
 * DO NOT EDIT MANUALLY.
 * Refer to: https://github.com/FenrirServer/Cloud.SdkTemplates
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Fenrir.Api.Model;
using Fenrir.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Fenrir.Api.Test.Model
{
    /// <summary>
    ///  Class for testing ApplicationInstancePort
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ApplicationInstancePortTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ApplicationInstancePort
        //private ApplicationInstancePort instance;

        public ApplicationInstancePortTests()
        {
            // TODO uncomment below to create an instance of ApplicationInstancePort
            //instance = new ApplicationInstancePort();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ApplicationInstancePort
        /// </summary>
        [Fact]
        public void ApplicationInstancePortInstanceTest()
        {
            // TODO uncomment below to test "IsType" ApplicationInstancePort
            //Assert.IsType<ApplicationInstancePort>(instance);
        }

        /// <summary>
        /// Test the property 'Protocol'
        /// </summary>
        [Fact]
        public void ProtocolTest()
        {
            // TODO unit test for the property 'Protocol'
        }

        /// <summary>
        /// Test the property 'PublishedPort'
        /// </summary>
        [Fact]
        public void PublishedPortTest()
        {
            // TODO unit test for the property 'PublishedPort'
        }

        /// <summary>
        /// Test the property 'TargetPort'
        /// </summary>
        [Fact]
        public void TargetPortTest()
        {
            // TODO unit test for the property 'TargetPort'
        }
    }
}
