/*
 * Fenrir Api
 * 
 * This file was automatically generated using openapi generator. 
 * DO NOT EDIT MANUALLY.
 * Refer to: https://github.com/FenrirServer/Cloud.SdkTemplates
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Fenrir.Api.Model;
using Fenrir.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Fenrir.Api.Test.Model
{
    /// <summary>
    ///  Class for testing ApplicationStatsResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ApplicationStatsResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ApplicationStatsResponse
        //private ApplicationStatsResponse instance;

        public ApplicationStatsResponseTests()
        {
            // TODO uncomment below to create an instance of ApplicationStatsResponse
            //instance = new ApplicationStatsResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ApplicationStatsResponse
        /// </summary>
        [Fact]
        public void ApplicationStatsResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" ApplicationStatsResponse
            //Assert.IsType<ApplicationStatsResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Stats'
        /// </summary>
        [Fact]
        public void StatsTest()
        {
            // TODO unit test for the property 'Stats'
        }
    }
}
