/*
 * Fenrir Api
 * 
 * This file was automatically generated using openapi generator. 
 * DO NOT EDIT MANUALLY.
 * Refer to: https://github.com/FenrirServer/Cloud.SdkTemplates
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Fenrir.Api.Model;
using Fenrir.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Fenrir.Api.Test.Model
{
    /// <summary>
    ///  Class for testing ApplicationResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ApplicationResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ApplicationResponse
        //private ApplicationResponse instance;

        public ApplicationResponseTests()
        {
            // TODO uncomment below to create an instance of ApplicationResponse
            //instance = new ApplicationResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ApplicationResponse
        /// </summary>
        [Fact]
        public void ApplicationResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" ApplicationResponse
            //Assert.IsType<ApplicationResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Application'
        /// </summary>
        [Fact]
        public void ApplicationTest()
        {
            // TODO unit test for the property 'Application'
        }
    }
}
