/*
 * Fenrir Api
 * 
 * This file was automatically generated using openapi generator. 
 * DO NOT EDIT MANUALLY.
 * Refer to: https://github.com/FenrirServer/Cloud.SdkTemplates
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Fenrir.Api.Model;
using Fenrir.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Fenrir.Api.Test.Model
{
    /// <summary>
    ///  Class for testing ApplicationConfigurationListResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ApplicationConfigurationListResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ApplicationConfigurationListResponse
        //private ApplicationConfigurationListResponse instance;

        public ApplicationConfigurationListResponseTests()
        {
            // TODO uncomment below to create an instance of ApplicationConfigurationListResponse
            //instance = new ApplicationConfigurationListResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ApplicationConfigurationListResponse
        /// </summary>
        [Fact]
        public void ApplicationConfigurationListResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" ApplicationConfigurationListResponse
            //Assert.IsType<ApplicationConfigurationListResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Configurations'
        /// </summary>
        [Fact]
        public void ConfigurationsTest()
        {
            // TODO unit test for the property 'Configurations'
        }
    }
}
