/*
 * Fenrir Api
 * 
 * This file was automatically generated using openapi generator. 
 * DO NOT EDIT MANUALLY.
 * Refer to: https://github.com/FenrirServer/Cloud.SdkTemplates
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Fenrir.Api.Model;
using Fenrir.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Fenrir.Api.Test.Model
{
    /// <summary>
    ///  Class for testing ApplicationInstance
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ApplicationInstanceTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ApplicationInstance
        //private ApplicationInstance instance;

        public ApplicationInstanceTests()
        {
            // TODO uncomment below to create an instance of ApplicationInstance
            //instance = new ApplicationInstance();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ApplicationInstance
        /// </summary>
        [Fact]
        public void ApplicationInstanceInstanceTest()
        {
            // TODO uncomment below to test "IsType" ApplicationInstance
            //Assert.IsType<ApplicationInstance>(instance);
        }

        /// <summary>
        /// Test the property 'ApplicationUuid'
        /// </summary>
        [Fact]
        public void ApplicationUuidTest()
        {
            // TODO unit test for the property 'ApplicationUuid'
        }

        /// <summary>
        /// Test the property 'ContainerId'
        /// </summary>
        [Fact]
        public void ContainerIdTest()
        {
            // TODO unit test for the property 'ContainerId'
        }

        /// <summary>
        /// Test the property 'Created'
        /// </summary>
        [Fact]
        public void CreatedTest()
        {
            // TODO unit test for the property 'Created'
        }

        /// <summary>
        /// Test the property 'DeploymentUuid'
        /// </summary>
        [Fact]
        public void DeploymentUuidTest()
        {
            // TODO unit test for the property 'DeploymentUuid'
        }

        /// <summary>
        /// Test the property 'DesiredState'
        /// </summary>
        [Fact]
        public void DesiredStateTest()
        {
            // TODO unit test for the property 'DesiredState'
        }

        /// <summary>
        /// Test the property 'Hostname'
        /// </summary>
        [Fact]
        public void HostnameTest()
        {
            // TODO unit test for the property 'Hostname'
        }

        /// <summary>
        /// Test the property 'Ports'
        /// </summary>
        [Fact]
        public void PortsTest()
        {
            // TODO unit test for the property 'Ports'
        }

        /// <summary>
        /// Test the property 'State'
        /// </summary>
        [Fact]
        public void StateTest()
        {
            // TODO unit test for the property 'State'
        }

        /// <summary>
        /// Test the property 'Updated'
        /// </summary>
        [Fact]
        public void UpdatedTest()
        {
            // TODO unit test for the property 'Updated'
        }

        /// <summary>
        /// Test the property 'Uuid'
        /// </summary>
        [Fact]
        public void UuidTest()
        {
            // TODO unit test for the property 'Uuid'
        }
    }
}
