/*
 * Fenrir Api
 * 
 * This file was automatically generated using openapi generator. 
 * DO NOT EDIT MANUALLY.
 * Refer to: https://github.com/FenrirServer/Cloud.SdkTemplates
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Fenrir.Api.Model;
using Fenrir.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Fenrir.Api.Test.Model
{
    /// <summary>
    ///  Class for testing ApplicationListResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ApplicationListResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ApplicationListResponse
        //private ApplicationListResponse instance;

        public ApplicationListResponseTests()
        {
            // TODO uncomment below to create an instance of ApplicationListResponse
            //instance = new ApplicationListResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ApplicationListResponse
        /// </summary>
        [Fact]
        public void ApplicationListResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" ApplicationListResponse
            //Assert.IsType<ApplicationListResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Applications'
        /// </summary>
        [Fact]
        public void ApplicationsTest()
        {
            // TODO unit test for the property 'Applications'
        }
    }
}
