/*
 * Fenrir Api
 * 
 * This file was automatically generated using openapi generator. 
 * DO NOT EDIT MANUALLY.
 * Refer to: https://github.com/FenrirServer/Cloud.SdkTemplates
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Fenrir.Api.Model;
using Fenrir.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Fenrir.Api.Test.Model
{
    /// <summary>
    ///  Class for testing BadRequestResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class BadRequestResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for BadRequestResponse
        //private BadRequestResponse instance;

        public BadRequestResponseTests()
        {
            // TODO uncomment below to create an instance of BadRequestResponse
            //instance = new BadRequestResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of BadRequestResponse
        /// </summary>
        [Fact]
        public void BadRequestResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" BadRequestResponse
            //Assert.IsType<BadRequestResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Errors'
        /// </summary>
        [Fact]
        public void ErrorsTest()
        {
            // TODO unit test for the property 'Errors'
        }

        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Fact]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }
    }
}
