/*
 * Fenrir Api
 * 
 * This file was automatically generated using openapi generator. 
 * DO NOT EDIT MANUALLY.
 * Refer to: https://github.com/FenrirServer/Cloud.SdkTemplates
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Fenrir.Api.Model;
using Fenrir.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Fenrir.Api.Test.Model
{
    /// <summary>
    ///  Class for testing DeploymentResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DeploymentResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DeploymentResponse
        //private DeploymentResponse instance;

        public DeploymentResponseTests()
        {
            // TODO uncomment below to create an instance of DeploymentResponse
            //instance = new DeploymentResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DeploymentResponse
        /// </summary>
        [Fact]
        public void DeploymentResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" DeploymentResponse
            //Assert.IsType<DeploymentResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Deployment'
        /// </summary>
        [Fact]
        public void DeploymentTest()
        {
            // TODO unit test for the property 'Deployment'
        }
    }
}
