/*
 * Fenrir Api
 * 
 * This file was automatically generated using openapi generator. 
 * DO NOT EDIT MANUALLY.
 * Refer to: https://github.com/FenrirServer/Cloud.SdkTemplates
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Fenrir.Api.Model;
using Fenrir.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Fenrir.Api.Test.Model
{
    /// <summary>
    ///  Class for testing Deployment
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DeploymentTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Deployment
        //private Deployment instance;

        public DeploymentTests()
        {
            // TODO uncomment below to create an instance of Deployment
            //instance = new Deployment();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Deployment
        /// </summary>
        [Fact]
        public void DeploymentInstanceTest()
        {
            // TODO uncomment below to test "IsType" Deployment
            //Assert.IsType<Deployment>(instance);
        }

        /// <summary>
        /// Test the property 'ApplicationUuid'
        /// </summary>
        [Fact]
        public void ApplicationUuidTest()
        {
            // TODO unit test for the property 'ApplicationUuid'
        }

        /// <summary>
        /// Test the property 'ConfigurationUuid'
        /// </summary>
        [Fact]
        public void ConfigurationUuidTest()
        {
            // TODO unit test for the property 'ConfigurationUuid'
        }

        /// <summary>
        /// Test the property 'Created'
        /// </summary>
        [Fact]
        public void CreatedTest()
        {
            // TODO unit test for the property 'Created'
        }

        /// <summary>
        /// Test the property 'ImageTag'
        /// </summary>
        [Fact]
        public void ImageTagTest()
        {
            // TODO unit test for the property 'ImageTag'
        }

        /// <summary>
        /// Test the property 'Label'
        /// </summary>
        [Fact]
        public void LabelTest()
        {
            // TODO unit test for the property 'Label'
        }

        /// <summary>
        /// Test the property 'Updated'
        /// </summary>
        [Fact]
        public void UpdatedTest()
        {
            // TODO unit test for the property 'Updated'
        }

        /// <summary>
        /// Test the property 'Uuid'
        /// </summary>
        [Fact]
        public void UuidTest()
        {
            // TODO unit test for the property 'Uuid'
        }
    }
}
