/*
 * Fenrir Api
 * 
 * This file was automatically generated using openapi generator. 
 * DO NOT EDIT MANUALLY.
 * Refer to: https://github.com/FenrirServer/Cloud.SdkTemplates
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Fenrir.Api.Model;
using Fenrir.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Fenrir.Api.Test.Model
{
    /// <summary>
    ///  Class for testing DeploymentListResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DeploymentListResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DeploymentListResponse
        //private DeploymentListResponse instance;

        public DeploymentListResponseTests()
        {
            // TODO uncomment below to create an instance of DeploymentListResponse
            //instance = new DeploymentListResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DeploymentListResponse
        /// </summary>
        [Fact]
        public void DeploymentListResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" DeploymentListResponse
            //Assert.IsType<DeploymentListResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Deployments'
        /// </summary>
        [Fact]
        public void DeploymentsTest()
        {
            // TODO unit test for the property 'Deployments'
        }
    }
}
