/*
 * Fenrir Api
 * 
 * This file was automatically generated using openapi generator. 
 * DO NOT EDIT MANUALLY.
 * Refer to: https://github.com/FenrirServer/Cloud.SdkTemplates
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Fenrir.Api.Model;
using Fenrir.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Fenrir.Api.Test.Model
{
    /// <summary>
    ///  Class for testing ImageListResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ImageListResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ImageListResponse
        //private ImageListResponse instance;

        public ImageListResponseTests()
        {
            // TODO uncomment below to create an instance of ImageListResponse
            //instance = new ImageListResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ImageListResponse
        /// </summary>
        [Fact]
        public void ImageListResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" ImageListResponse
            //Assert.IsType<ImageListResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Images'
        /// </summary>
        [Fact]
        public void ImagesTest()
        {
            // TODO unit test for the property 'Images'
        }
    }
}
