/*
 * Fenrir Api
 * 
 * This file was automatically generated using openapi generator. 
 * DO NOT EDIT MANUALLY.
 * Refer to: https://github.com/FenrirServer/Cloud.SdkTemplates
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Fenrir.Api.Model;
using Fenrir.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Fenrir.Api.Test.Model
{
    /// <summary>
    ///  Class for testing Image
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ImageTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Image
        //private Image instance;

        public ImageTests()
        {
            // TODO uncomment below to create an instance of Image
            //instance = new Image();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Image
        /// </summary>
        [Fact]
        public void ImageInstanceTest()
        {
            // TODO uncomment below to test "IsType" Image
            //Assert.IsType<Image>(instance);
        }

        /// <summary>
        /// Test the property 'Created'
        /// </summary>
        [Fact]
        public void CreatedTest()
        {
            // TODO unit test for the property 'Created'
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'LastTagTime'
        /// </summary>
        [Fact]
        public void LastTagTimeTest()
        {
            // TODO unit test for the property 'LastTagTime'
        }

        /// <summary>
        /// Test the property 'Size'
        /// </summary>
        [Fact]
        public void SizeTest()
        {
            // TODO unit test for the property 'Size'
        }

        /// <summary>
        /// Test the property 'Tags'
        /// </summary>
        [Fact]
        public void TagsTest()
        {
            // TODO unit test for the property 'Tags'
        }
    }
}
