/*
 * Fenrir Api
 * 
 * This file was automatically generated using openapi generator. 
 * DO NOT EDIT MANUALLY.
 * Refer to: https://github.com/FenrirServer/Cloud.SdkTemplates
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Fenrir.Api.Model;
using Fenrir.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Fenrir.Api.Test.Model
{
    /// <summary>
    ///  Class for testing InstanceLogs
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class InstanceLogsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for InstanceLogs
        //private InstanceLogs instance;

        public InstanceLogsTests()
        {
            // TODO uncomment below to create an instance of InstanceLogs
            //instance = new InstanceLogs();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of InstanceLogs
        /// </summary>
        [Fact]
        public void InstanceLogsInstanceTest()
        {
            // TODO uncomment below to test "IsType" InstanceLogs
            //Assert.IsType<InstanceLogs>(instance);
        }

        /// <summary>
        /// Test the property 'Url'
        /// </summary>
        [Fact]
        public void UrlTest()
        {
            // TODO unit test for the property 'Url'
        }
    }
}
