/*
 * Fenrir Api
 * 
 * This file was automatically generated using openapi generator. 
 * DO NOT EDIT MANUALLY.
 * Refer to: https://github.com/FenrirServer/Cloud.SdkTemplates
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Fenrir.Api.Model;
using Fenrir.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Fenrir.Api.Test.Model
{
    /// <summary>
    ///  Class for testing InstanceLogsPreview
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class InstanceLogsPreviewTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for InstanceLogsPreview
        //private InstanceLogsPreview instance;

        public InstanceLogsPreviewTests()
        {
            // TODO uncomment below to create an instance of InstanceLogsPreview
            //instance = new InstanceLogsPreview();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of InstanceLogsPreview
        /// </summary>
        [Fact]
        public void InstanceLogsPreviewInstanceTest()
        {
            // TODO uncomment below to test "IsType" InstanceLogsPreview
            //Assert.IsType<InstanceLogsPreview>(instance);
        }

        /// <summary>
        /// Test the property 'LogLines'
        /// </summary>
        [Fact]
        public void LogLinesTest()
        {
            // TODO unit test for the property 'LogLines'
        }
    }
}
