/*
 * Fenrir Api
 * 
 * This file was automatically generated using openapi generator. 
 * DO NOT EDIT MANUALLY.
 * Refer to: https://github.com/FenrirServer/Cloud.SdkTemplates
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Fenrir.Api.Model;
using Fenrir.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Fenrir.Api.Test.Model
{
    /// <summary>
    ///  Class for testing MatchmakingQueueConfiguration
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class MatchmakingQueueConfigurationTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for MatchmakingQueueConfiguration
        //private MatchmakingQueueConfiguration instance;

        public MatchmakingQueueConfigurationTests()
        {
            // TODO uncomment below to create an instance of MatchmakingQueueConfiguration
            //instance = new MatchmakingQueueConfiguration();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of MatchmakingQueueConfiguration
        /// </summary>
        [Fact]
        public void MatchmakingQueueConfigurationInstanceTest()
        {
            // TODO uncomment below to test "IsType" MatchmakingQueueConfiguration
            //Assert.IsType<MatchmakingQueueConfiguration>(instance);
        }

        /// <summary>
        /// Test the property 'ConfirmationRequired'
        /// </summary>
        [Fact]
        public void ConfirmationRequiredTest()
        {
            // TODO unit test for the property 'ConfirmationRequired'
        }

        /// <summary>
        /// Test the property 'ConfirmationTimeSeconds'
        /// </summary>
        [Fact]
        public void ConfirmationTimeSecondsTest()
        {
            // TODO unit test for the property 'ConfirmationTimeSeconds'
        }

        /// <summary>
        /// Test the property 'Created'
        /// </summary>
        [Fact]
        public void CreatedTest()
        {
            // TODO unit test for the property 'Created'
        }

        /// <summary>
        /// Test the property 'DeploymentUuid'
        /// </summary>
        [Fact]
        public void DeploymentUuidTest()
        {
            // TODO unit test for the property 'DeploymentUuid'
        }

        /// <summary>
        /// Test the property 'PlayerProperties'
        /// </summary>
        [Fact]
        public void PlayerPropertiesTest()
        {
            // TODO unit test for the property 'PlayerProperties'
        }

        /// <summary>
        /// Test the property 'PlayerRules'
        /// </summary>
        [Fact]
        public void PlayerRulesTest()
        {
            // TODO unit test for the property 'PlayerRules'
        }

        /// <summary>
        /// Test the property 'TeamRules'
        /// </summary>
        [Fact]
        public void TeamRulesTest()
        {
            // TODO unit test for the property 'TeamRules'
        }

        /// <summary>
        /// Test the property 'Teams'
        /// </summary>
        [Fact]
        public void TeamsTest()
        {
            // TODO unit test for the property 'Teams'
        }

        /// <summary>
        /// Test the property 'Uuid'
        /// </summary>
        [Fact]
        public void UuidTest()
        {
            // TODO unit test for the property 'Uuid'
        }

        /// <summary>
        /// Test the property 'VarVersion'
        /// </summary>
        [Fact]
        public void VarVersionTest()
        {
            // TODO unit test for the property 'VarVersion'
        }
    }
}
