/*
 * Fenrir Api
 * 
 * This file was automatically generated using openapi generator. 
 * DO NOT EDIT MANUALLY.
 * Refer to: https://github.com/FenrirServer/Cloud.SdkTemplates
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Fenrir.Api.Model;
using Fenrir.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Fenrir.Api.Test.Model
{
    /// <summary>
    ///  Class for testing MatchmakingQueueConfigurationPlayerRule
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class MatchmakingQueueConfigurationPlayerRuleTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for MatchmakingQueueConfigurationPlayerRule
        //private MatchmakingQueueConfigurationPlayerRule instance;

        public MatchmakingQueueConfigurationPlayerRuleTests()
        {
            // TODO uncomment below to create an instance of MatchmakingQueueConfigurationPlayerRule
            //instance = new MatchmakingQueueConfigurationPlayerRule();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of MatchmakingQueueConfigurationPlayerRule
        /// </summary>
        [Fact]
        public void MatchmakingQueueConfigurationPlayerRuleInstanceTest()
        {
            // TODO uncomment below to test "IsType" MatchmakingQueueConfigurationPlayerRule
            //Assert.IsType<MatchmakingQueueConfigurationPlayerRule>(instance);
        }

        /// <summary>
        /// Test the property 'DifferenceValue'
        /// </summary>
        [Fact]
        public void DifferenceValueTest()
        {
            // TODO unit test for the property 'DifferenceValue'
        }

        /// <summary>
        /// Test the property 'PropertyKey'
        /// </summary>
        [Fact]
        public void PropertyKeyTest()
        {
            // TODO unit test for the property 'PropertyKey'
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
    }
}
