/*
 * Fenrir Api
 * 
 * This file was automatically generated using openapi generator. 
 * DO NOT EDIT MANUALLY.
 * Refer to: https://github.com/FenrirServer/Cloud.SdkTemplates
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Fenrir.Api.Model;
using Fenrir.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Fenrir.Api.Test.Model
{
    /// <summary>
    ///  Class for testing MatchmakingQueueConfigurationResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class MatchmakingQueueConfigurationResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for MatchmakingQueueConfigurationResponse
        //private MatchmakingQueueConfigurationResponse instance;

        public MatchmakingQueueConfigurationResponseTests()
        {
            // TODO uncomment below to create an instance of MatchmakingQueueConfigurationResponse
            //instance = new MatchmakingQueueConfigurationResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of MatchmakingQueueConfigurationResponse
        /// </summary>
        [Fact]
        public void MatchmakingQueueConfigurationResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" MatchmakingQueueConfigurationResponse
            //Assert.IsType<MatchmakingQueueConfigurationResponse>(instance);
        }

        /// <summary>
        /// Test the property 'VarConfiguration'
        /// </summary>
        [Fact]
        public void VarConfigurationTest()
        {
            // TODO unit test for the property 'VarConfiguration'
        }
    }
}
