/*
 * Fenrir Api
 * 
 * This file was automatically generated using openapi generator. 
 * DO NOT EDIT MANUALLY.
 * Refer to: https://github.com/FenrirServer/Cloud.SdkTemplates
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Fenrir.Api.Model;
using Fenrir.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Fenrir.Api.Test.Model
{
    /// <summary>
    ///  Class for testing MatchmakingQueueResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class MatchmakingQueueResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for MatchmakingQueueResponse
        //private MatchmakingQueueResponse instance;

        public MatchmakingQueueResponseTests()
        {
            // TODO uncomment below to create an instance of MatchmakingQueueResponse
            //instance = new MatchmakingQueueResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of MatchmakingQueueResponse
        /// </summary>
        [Fact]
        public void MatchmakingQueueResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" MatchmakingQueueResponse
            //Assert.IsType<MatchmakingQueueResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Queue'
        /// </summary>
        [Fact]
        public void QueueTest()
        {
            // TODO unit test for the property 'Queue'
        }
    }
}
