/*
 * Fenrir Api
 * 
 * This file was automatically generated using openapi generator. 
 * DO NOT EDIT MANUALLY.
 * Refer to: https://github.com/FenrirServer/Cloud.SdkTemplates
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Fenrir.Api.Model;
using Fenrir.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Fenrir.Api.Test.Model
{
    /// <summary>
    ///  Class for testing MatchmakingQueueConfigurationPlayerProperty
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class MatchmakingQueueConfigurationPlayerPropertyTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for MatchmakingQueueConfigurationPlayerProperty
        //private MatchmakingQueueConfigurationPlayerProperty instance;

        public MatchmakingQueueConfigurationPlayerPropertyTests()
        {
            // TODO uncomment below to create an instance of MatchmakingQueueConfigurationPlayerProperty
            //instance = new MatchmakingQueueConfigurationPlayerProperty();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of MatchmakingQueueConfigurationPlayerProperty
        /// </summary>
        [Fact]
        public void MatchmakingQueueConfigurationPlayerPropertyInstanceTest()
        {
            // TODO uncomment below to test "IsType" MatchmakingQueueConfigurationPlayerProperty
            //Assert.IsType<MatchmakingQueueConfigurationPlayerProperty>(instance);
        }

        /// <summary>
        /// Test the property 'DefaultValue'
        /// </summary>
        [Fact]
        public void DefaultValueTest()
        {
            // TODO unit test for the property 'DefaultValue'
        }

        /// <summary>
        /// Test the property 'Key'
        /// </summary>
        [Fact]
        public void KeyTest()
        {
            // TODO unit test for the property 'Key'
        }

        /// <summary>
        /// Test the property 'Required'
        /// </summary>
        [Fact]
        public void RequiredTest()
        {
            // TODO unit test for the property 'Required'
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
    }
}
