/*
 * Fenrir Api
 * 
 * This file was automatically generated using openapi generator. 
 * DO NOT EDIT MANUALLY.
 * Refer to: https://github.com/FenrirServer/Cloud.SdkTemplates
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Fenrir.Api.Model;
using Fenrir.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Fenrir.Api.Test.Model
{
    /// <summary>
    ///  Class for testing PortConfiguration
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PortConfigurationTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PortConfiguration
        //private PortConfiguration instance;

        public PortConfigurationTests()
        {
            // TODO uncomment below to create an instance of PortConfiguration
            //instance = new PortConfiguration();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PortConfiguration
        /// </summary>
        [Fact]
        public void PortConfigurationInstanceTest()
        {
            // TODO uncomment below to test "IsType" PortConfiguration
            //Assert.IsType<PortConfiguration>(instance);
        }

        /// <summary>
        /// Test the property 'PortNumber'
        /// </summary>
        [Fact]
        public void PortNumberTest()
        {
            // TODO unit test for the property 'PortNumber'
        }

        /// <summary>
        /// Test the property 'Protocol'
        /// </summary>
        [Fact]
        public void ProtocolTest()
        {
            // TODO unit test for the property 'Protocol'
        }
    }
}
